### ISSUE TITLE
Release binaries?

### ISSUE THREAD

**Issue by jcs090218** [nobody-famous/alive-lsp#60]
Can we build this project to executable? So it's easier to use in other editors.

For example:

```
$ alive-lsp --stdio
```

**Comment by jcs090218** [comment]
Do you need to cross compile it? Couldn't we use GitHub Actions and build from native? 🤔

**Comment by nobody-famous** [comment]
It would need to compile for all the os and architectures SBCL supports, which is pretty extensive. I don't really see an upside to it, so don't want to have to maintain it. It sounds like a lot of headache for very little benefit. If somebody wants to create a repo to make binaries available, they should be able to.
