### ISSUE TITLE
No handler for $/cancelRequest

### ISSUE THREAD

**Issue by dennis-barrett** [nobody-famous/alive-lsp#61]
Good day,

Periodically VS Code sends a `$/cancelRequest` to Alive LSP, for which it does not have a handler. This results in an error message from the Alive LSP: `No handler for $/cancelRequest`.

Does it make sense to implement a handler for `$/cancelRequest` in Alive LSP (cf. [https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#dollarRequests](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#dollarRequests))? Or perhaps $-requests could be explicitly discarded, so they don't cause an error message?

(Happy to take a swing at a PR for the above, just want to get your thoughts as I'm not familiar with the LSP spec.)

Kind regards,
Dennis

**Comment by dennis-barrett** [comment]
The reason I'm interested in this is because I'm writing an app using [Croatoan](https://github.com/McParen/croatoan). Similar to how [this page](https://github.com/McParen/croatoan/blob/a1924cc5e01a5218e55fbe668abde3fafac89c61/doc/slime.md) describes working with Croatoan and swank/slime, I have my app start an Alive LSP instance, and then I connect to it remotely from VS Code. The above error message gets printed over the app's TUI.

**Comment by nobody-famous** [comment]
There isn't a good way to actually cancel the requests, so ignoring it works. The client should ignore any results that come in after the cancel.

**Comment by dennis-barrett** [comment]
Could I add an empty handler so it doesn't trigger the error message? (Or otherwise just ignore dollar requests, without triggering the error?)

**Comment by nobody-famous** [comment]
Yeah, since it's a notification it can be ignored. It'll be easy to add, I just haven't had time to do it, yet. In session.lisp, it already ignores things like "$/setTrace" so it's just a matter of adding a line for "$/cancelRequest".

**Comment by dennis-barrett** [comment]
@nobody-famous thank you for updating the handlers🙏 (I was just about to take a look at creating a PR when I saw you'd already done it.)
